/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tcc.ui;

/**
 *
 * @author Affero
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        JPanelCadastro = new javax.swing.JPanel();
        btnBusca = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        eCodigo = new javax.swing.JTextField();
        lblDataAlteracao = new javax.swing.JLabel();
        rdPF = new javax.swing.JRadioButton();
        rdPJ = new javax.swing.JRadioButton();
        lblCNPJ = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        eNome = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        eEndereco = new javax.swing.JTextField();
        eNum = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        eBairro = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        eCidade = new javax.swing.JTextField();
        lblUF = new javax.swing.JLabel();
        eDateAlt = new javax.swing.JFormattedTextField();
        eCNPJ = new javax.swing.JFormattedTextField();
        eCEP = new javax.swing.JFormattedTextField();
        lblTelefone = new javax.swing.JLabel();
        eTel = new javax.swing.JFormattedTextField();
        cbUF = new javax.swing.JComboBox();
        lblEmail = new javax.swing.JLabel();
        eEmail = new javax.swing.JTextField();
        lblCel = new javax.swing.JLabel();
        eCel = new javax.swing.JFormattedTextField();
        btnInserir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        JMenuBarra = new javax.swing.JMenuBar();
        JMArquivo = new javax.swing.JMenu();
        aAbrir = new javax.swing.JMenuItem();
        aNovo = new javax.swing.JMenuItem();
        aSalvar = new javax.swing.JMenuItem();
        aSalvarComo = new javax.swing.JMenuItem();
        EPropriedades = new javax.swing.JMenu();
        eDesfazer = new javax.swing.JMenuItem();
        eRefazer = new javax.swing.JMenuItem();
        eCortar = new javax.swing.JMenuItem();
        eCopiar = new javax.swing.JMenuItem();
        eColar = new javax.swing.JMenuItem();
        JMExibir = new javax.swing.JMenu();
        eFerramentas = new javax.swing.JMenuItem();
        ePropr = new javax.swing.JMenuItem();
        eStatus = new javax.swing.JMenuItem();
        eIGrandes = new javax.swing.JMenuItem();
        eIPequenos = new javax.swing.JMenuItem();
        eLista = new javax.swing.JMenuItem();
        eDetalhe = new javax.swing.JMenuItem();
        eClassificar = new javax.swing.JMenuItem();
        JMAjuda = new javax.swing.JMenu();
        aSobre = new javax.swing.JMenuItem();
        aServicosSup = new javax.swing.JMenuItem();
        aAtalhos = new javax.swing.JMenuItem();

        setTitle("Cadastro de Clientes");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Menu"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        JPanelCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPanelCadastro.setLayout(null);

        btnBusca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBusca.setText("Busca");
        JPanelCadastro.add(btnBusca);
        btnBusca.setBounds(180, 30, 86, 30);

        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCodigo.setText("Código");
        JPanelCadastro.add(lblCodigo);
        lblCodigo.setBounds(30, 30, 60, 22);

        eCodigo.setName("eCodigo"); // NOI18N
        JPanelCadastro.add(eCodigo);
        eCodigo.setBounds(90, 30, 79, 30);

        lblDataAlteracao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDataAlteracao.setText("Data. Ult. Alteração");
        JPanelCadastro.add(lblDataAlteracao);
        lblDataAlteracao.setBounds(660, 30, 160, 26);

        buttonGroup2.add(rdPF);
        rdPF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdPF.setText("PF");
        rdPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPFActionPerformed(evt);
            }
        });
        JPanelCadastro.add(rdPF);
        rdPF.setBounds(270, 50, 45, 31);

        buttonGroup2.add(rdPJ);
        rdPJ.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdPJ.setText("PJ");
        JPanelCadastro.add(rdPJ);
        rdPJ.setBounds(270, 20, 43, 31);

        lblCNPJ.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCNPJ.setText("C.N.P.J/CPF");
        JPanelCadastro.add(lblCNPJ);
        lblCNPJ.setBounds(320, 30, 100, 22);

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNome.setText("Nome/Razão Social");
        JPanelCadastro.add(lblNome);
        lblNome.setBounds(30, 90, 160, 22);
        JPanelCadastro.add(eNome);
        eNome.setBounds(200, 90, 440, 30);

        lblEndereco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEndereco.setText("Endereço");
        JPanelCadastro.add(lblEndereco);
        lblEndereco.setBounds(30, 140, 72, 22);

        eEndereco.setPreferredSize(new java.awt.Dimension(14, 28));
        JPanelCadastro.add(eEndereco);
        eEndereco.setBounds(110, 140, 274, 30);

        eNum.setPreferredSize(new java.awt.Dimension(14, 28));
        JPanelCadastro.add(eNum);
        eNum.setBounds(420, 140, 43, 28);

        lblNumero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNumero.setText("Nº");
        JPanelCadastro.add(lblNumero);
        lblNumero.setBounds(390, 140, 21, 22);

        lblBairro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBairro.setText("Bairro");
        JPanelCadastro.add(lblBairro);
        lblBairro.setBounds(30, 190, 60, 22);

        eBairro.setPreferredSize(new java.awt.Dimension(14, 28));
        JPanelCadastro.add(eBairro);
        eBairro.setBounds(110, 190, 150, 30);

        lblCep.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCep.setText("Cep");
        JPanelCadastro.add(lblCep);
        lblCep.setBounds(480, 140, 30, 22);

        lblCidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCidade.setText("Cidade");
        JPanelCadastro.add(lblCidade);
        lblCidade.setBounds(280, 190, 60, 22);

        eCidade.setPreferredSize(new java.awt.Dimension(14, 28));
        JPanelCadastro.add(eCidade);
        eCidade.setBounds(350, 190, 160, 28);

        lblUF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUF.setText("UF");
        JPanelCadastro.add(lblUF);
        lblUF.setBounds(520, 190, 30, 22);

        try {
            eDateAlt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JPanelCadastro.add(eDateAlt);
        eDateAlt.setBounds(821, 30, 110, 30);

        try {
            eCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JPanelCadastro.add(eCNPJ);
        eCNPJ.setBounds(420, 30, 220, 30);

        try {
            eCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        eCEP.setPreferredSize(new java.awt.Dimension(14, 28));
        JPanelCadastro.add(eCEP);
        eCEP.setBounds(520, 140, 120, 28);

        lblTelefone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTelefone.setText("Telefone");
        JPanelCadastro.add(lblTelefone);
        lblTelefone.setBounds(30, 250, 68, 22);

        try {
            eTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        eTel.setPreferredSize(new java.awt.Dimension(14, 28));
        JPanelCadastro.add(eTel);
        eTel.setBounds(110, 250, 210, 28);

        cbUF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbUF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AL", "AP", "AM", "BA", "CE", "DF ", "ES", "GO", "MA", "MT", "MS", "MG", "PR", "PB", "PA", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "SP", "TO" }));
        cbUF.setName(""); // NOI18N
        cbUF.setPreferredSize(new java.awt.Dimension(14, 28));
        JPanelCadastro.add(cbUF);
        cbUF.setBounds(550, 190, 86, 30);

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmail.setText("E-mail");
        JPanelCadastro.add(lblEmail);
        lblEmail.setBounds(30, 300, 49, 22);

        eEmail.setPreferredSize(new java.awt.Dimension(14, 28));
        JPanelCadastro.add(eEmail);
        eEmail.setBounds(100, 300, 540, 30);

        lblCel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCel.setText("Celular");
        JPanelCadastro.add(lblCel);
        lblCel.setBounds(350, 250, 60, 22);

        try {
            eCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        eCel.setPreferredSize(new java.awt.Dimension(14, 28));
        JPanelCadastro.add(eCel);
        eCel.setBounds(420, 250, 220, 28);

        btnInserir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnInserir.setText("Inserir");
        JPanelCadastro.add(btnInserir);
        btnInserir.setBounds(20, 390, 86, 30);

        btnAtualizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAtualizar.setText("Atualizar");
        JPanelCadastro.add(btnAtualizar);
        btnAtualizar.setBounds(120, 390, 100, 30);

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnExcluir.setText("Excluir");
        JPanelCadastro.add(btnExcluir);
        btnExcluir.setBounds(230, 390, 86, 30);

        btnSair.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSair.setText("Sair");
        JPanelCadastro.add(btnSair);
        btnSair.setBounds(850, 390, 73, 30);

        getContentPane().add(JPanelCadastro);
        JPanelCadastro.setBounds(20, 20, 950, 450);

        JMArquivo.setText("Arquivo");

        aAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        aAbrir.setText("Abrir");
        aAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aAbrirActionPerformed(evt);
            }
        });
        JMArquivo.add(aAbrir);
        aAbrir.getAccessibleContext().setAccessibleDescription("");

        aNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        aNovo.setText("Novo");
        JMArquivo.add(aNovo);

        aSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        aSalvar.setText("Salvar");
        JMArquivo.add(aSalvar);

        aSalvarComo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        aSalvarComo.setText("Salvar Como");
        JMArquivo.add(aSalvarComo);

        JMenuBarra.add(JMArquivo);

        EPropriedades.setText("Editar");

        eDesfazer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        eDesfazer.setText("Desfazer");
        eDesfazer.setToolTipText("");
        EPropriedades.add(eDesfazer);

        eRefazer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        eRefazer.setText("Refazer");
        EPropriedades.add(eRefazer);

        eCortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        eCortar.setText("Cortar");
        EPropriedades.add(eCortar);

        eCopiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        eCopiar.setText("Copiar");
        EPropriedades.add(eCopiar);

        eColar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        eColar.setText("Colar");
        EPropriedades.add(eColar);

        JMenuBarra.add(EPropriedades);

        JMExibir.setText("Exibir");

        eFerramentas.setText("Barra de Ferramentas");
        JMExibir.add(eFerramentas);

        ePropr.setText("Barra de Propriedades");
        ePropr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eProprActionPerformed(evt);
            }
        });
        JMExibir.add(ePropr);

        eStatus.setText("Barra de Status");
        eStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eStatusActionPerformed(evt);
            }
        });
        JMExibir.add(eStatus);

        eIGrandes.setText("Ícones Grandes");
        eIGrandes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eIGrandesActionPerformed(evt);
            }
        });
        JMExibir.add(eIGrandes);

        eIPequenos.setText("Ícones Pequenos");
        JMExibir.add(eIPequenos);

        eLista.setText("Lista");
        JMExibir.add(eLista);

        eDetalhe.setText("Detalhe");
        JMExibir.add(eDetalhe);

        eClassificar.setText("Classificar Tudo");
        JMExibir.add(eClassificar);

        JMenuBarra.add(JMExibir);

        JMAjuda.setText("Ajuda");

        aSobre.setText("Sobre?");
        JMAjuda.add(aSobre);

        aServicosSup.setText("Serviços e Suporte");
        JMAjuda.add(aServicosSup);

        aAtalhos.setText("Atalhos do Teclado");
        JMAjuda.add(aAtalhos);

        JMenuBarra.add(JMAjuda);

        setJMenuBar(JMenuBarra);

        getAccessibleContext().setAccessibleDescription("");

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1016)/2, (screenSize.height-638)/2, 1016, 638);
    }// </editor-fold>//GEN-END:initComponents

    private void aAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aAbrirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aAbrirActionPerformed

    private void rdPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdPFActionPerformed

    private void eProprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eProprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eProprActionPerformed

    private void eStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eStatusActionPerformed

    private void eIGrandesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eIGrandesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eIGrandesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu EPropriedades;
    private javax.swing.JMenu JMAjuda;
    private javax.swing.JMenu JMArquivo;
    private javax.swing.JMenu JMExibir;
    private javax.swing.JMenuBar JMenuBarra;
    private javax.swing.JPanel JPanelCadastro;
    private javax.swing.JMenuItem aAbrir;
    private javax.swing.JMenuItem aAtalhos;
    private javax.swing.JMenuItem aNovo;
    private javax.swing.JMenuItem aSalvar;
    private javax.swing.JMenuItem aSalvarComo;
    private javax.swing.JMenuItem aServicosSup;
    private javax.swing.JMenuItem aSobre;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cbUF;
    private javax.swing.JTextField eBairro;
    private javax.swing.JFormattedTextField eCEP;
    private javax.swing.JFormattedTextField eCNPJ;
    private javax.swing.JFormattedTextField eCel;
    private javax.swing.JTextField eCidade;
    private javax.swing.JMenuItem eClassificar;
    private javax.swing.JTextField eCodigo;
    private javax.swing.JMenuItem eColar;
    private javax.swing.JMenuItem eCopiar;
    private javax.swing.JMenuItem eCortar;
    private javax.swing.JFormattedTextField eDateAlt;
    private javax.swing.JMenuItem eDesfazer;
    private javax.swing.JMenuItem eDetalhe;
    private javax.swing.JTextField eEmail;
    private javax.swing.JTextField eEndereco;
    private javax.swing.JMenuItem eFerramentas;
    private javax.swing.JMenuItem eIGrandes;
    private javax.swing.JMenuItem eIPequenos;
    private javax.swing.JMenuItem eLista;
    private javax.swing.JTextField eNome;
    private javax.swing.JTextField eNum;
    private javax.swing.JMenuItem ePropr;
    private javax.swing.JMenuItem eRefazer;
    private javax.swing.JMenuItem eStatus;
    private javax.swing.JFormattedTextField eTel;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblCel;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDataAlteracao;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblUF;
    private javax.swing.JRadioButton rdPF;
    private javax.swing.JRadioButton rdPJ;
    // End of variables declaration//GEN-END:variables
}
