/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tcc.ui;

import java.util.Date;
import tcc.dao.FuncionarioDAO;
import tcc.model.EnderecoFuncionario;
import tcc.model.Funcionario;

/**
 *
 * @author Affero
 */
public class CadastroFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        JPanelCadastro = new javax.swing.JPanel();
        bntBusca = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        fCodigo = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        fNome = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        fEmail = new javax.swing.JTextField();
        btnInserir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblNacionalidade = new javax.swing.JLabel();
        fNasciona = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        fCPF = new javax.swing.JFormattedTextField();
        fPessoa = new javax.swing.JComboBox();
        lblRG = new javax.swing.JLabel();
        fRG = new javax.swing.JFormattedTextField();
        fCTPS = new javax.swing.JFormattedTextField();
        lblCTPS = new javax.swing.JLabel();
        lblCivil = new javax.swing.JLabel();
        fCivil = new javax.swing.JComboBox();
        lblProf = new javax.swing.JLabel();
        fProfissao = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        fNasc = new javax.swing.JFormattedTextField();
        lblSexo = new javax.swing.JLabel();
        fMasc = new javax.swing.JComboBox();
        lblTel = new javax.swing.JLabel();
        fTel = new javax.swing.JFormattedTextField();
        lblCel = new javax.swing.JLabel();
        fCel = new javax.swing.JFormattedTextField();
        JMenuBarra = new javax.swing.JMenuBar();
        jmArquivo = new javax.swing.JMenu();
        aAbrir = new javax.swing.JMenuItem();
        aNovo = new javax.swing.JMenuItem();
        aSalvar = new javax.swing.JMenuItem();
        aSalvarComo = new javax.swing.JMenuItem();
        ePropriedades = new javax.swing.JMenu();
        eDesfazer = new javax.swing.JMenuItem();
        eRefazer = new javax.swing.JMenuItem();
        eCortar = new javax.swing.JMenuItem();
        eCopiar = new javax.swing.JMenuItem();
        eColar = new javax.swing.JMenuItem();
        JMExibir = new javax.swing.JMenu();
        eFerramentas = new javax.swing.JMenuItem();
        ePropr = new javax.swing.JMenuItem();
        eStatus = new javax.swing.JMenuItem();
        eIGrandes = new javax.swing.JMenuItem();
        eIPequenos = new javax.swing.JMenuItem();
        eLista = new javax.swing.JMenuItem();
        eDetalhe = new javax.swing.JMenuItem();
        eClassificar = new javax.swing.JMenuItem();
        JMAjuda = new javax.swing.JMenu();
        aSobre = new javax.swing.JMenuItem();
        aServicosSup = new javax.swing.JMenuItem();
        aAtalhos = new javax.swing.JMenuItem();

        setTitle("Cadastro de Clientes");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Menu"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        JPanelCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPanelCadastro.setLayout(null);

        bntBusca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bntBusca.setText("Busca");
        JPanelCadastro.add(bntBusca);
        bntBusca.setBounds(250, 10, 90, 30);

        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCodigo.setText("Código");
        JPanelCadastro.add(lblCodigo);
        lblCodigo.setBounds(30, 10, 60, 22);

        fCodigo.setName("fCodigo"); // NOI18N
        JPanelCadastro.add(fCodigo);
        fCodigo.setBounds(150, 10, 79, 30);

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNome.setText("Nome");
        JPanelCadastro.add(lblNome);
        lblNome.setBounds(30, 50, 70, 22);
        JPanelCadastro.add(fNome);
        fNome.setBounds(150, 50, 490, 30);

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmail.setText("E-mail");
        JPanelCadastro.add(lblEmail);
        lblEmail.setBounds(30, 450, 49, 22);
        JPanelCadastro.add(fEmail);
        fEmail.setBounds(150, 450, 490, 30);

        btnInserir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        JPanelCadastro.add(btnInserir);
        btnInserir.setBounds(20, 530, 86, 30);

        btnAtualizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAtualizar.setText("Atualizar");
        JPanelCadastro.add(btnAtualizar);
        btnAtualizar.setBounds(120, 530, 100, 30);

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnExcluir.setText("Excluir");
        JPanelCadastro.add(btnExcluir);
        btnExcluir.setBounds(230, 530, 86, 30);

        btnSair.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSair.setText("Sair");
        JPanelCadastro.add(btnSair);
        btnSair.setBounds(560, 530, 73, 30);

        lblNacionalidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNacionalidade.setText("Nacionalidade");
        JPanelCadastro.add(lblNacionalidade);
        lblNacionalidade.setBounds(30, 90, 120, 22);
        JPanelCadastro.add(fNasciona);
        fNasciona.setBounds(150, 90, 210, 30);

        lblCPF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCPF.setText("CPF");
        JPanelCadastro.add(lblCPF);
        lblCPF.setBounds(30, 130, 30, 22);

        lblTipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTipo.setText("Tipo Pessoa");
        JPanelCadastro.add(lblTipo);
        lblTipo.setBounds(30, 170, 110, 30);

        try {
            fCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JPanelCadastro.add(fCPF);
        fCPF.setBounds(150, 130, 210, 30);

        fPessoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fPessoa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Física", "Juridica" }));
        JPanelCadastro.add(fPessoa);
        fPessoa.setBounds(150, 170, 210, 30);

        lblRG.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRG.setText("RG");
        JPanelCadastro.add(lblRG);
        lblRG.setBounds(30, 210, 30, 30);

        try {
            fRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-###-###/#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JPanelCadastro.add(fRG);
        fRG.setBounds(150, 210, 210, 30);
        JPanelCadastro.add(fCTPS);
        fCTPS.setBounds(150, 250, 210, 30);

        lblCTPS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCTPS.setText("Número CTPS");
        JPanelCadastro.add(lblCTPS);
        lblCTPS.setBounds(30, 250, 110, 30);

        lblCivil.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCivil.setText("Estado Civil");
        JPanelCadastro.add(lblCivil);
        lblCivil.setBounds(30, 290, 110, 22);

        fCivil.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Casado", "Solteiro" }));
        JPanelCadastro.add(fCivil);
        fCivil.setBounds(150, 290, 210, 30);

        lblProf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblProf.setText("Profissão");
        JPanelCadastro.add(lblProf);
        lblProf.setBounds(30, 330, 90, 22);
        JPanelCadastro.add(fProfissao);
        fProfissao.setBounds(150, 330, 490, 30);

        lblData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblData.setText("Data de Nasc");
        JPanelCadastro.add(lblData);
        lblData.setBounds(30, 370, 110, 30);

        try {
            fNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JPanelCadastro.add(fNasc);
        fNasc.setBounds(150, 370, 210, 30);

        lblSexo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSexo.setText("Sexo");
        JPanelCadastro.add(lblSexo);
        lblSexo.setBounds(30, 410, 60, 30);

        fMasc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fMasc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        JPanelCadastro.add(fMasc);
        fMasc.setBounds(150, 410, 210, 30);

        lblTel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTel.setText("Telefone");
        JPanelCadastro.add(lblTel);
        lblTel.setBounds(30, 490, 80, 30);

        try {
            fTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JPanelCadastro.add(fTel);
        fTel.setBounds(150, 490, 170, 30);

        lblCel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCel.setText("Celular");
        JPanelCadastro.add(lblCel);
        lblCel.setBounds(390, 490, 70, 30);

        try {
            fCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JPanelCadastro.add(fCel);
        fCel.setBounds(470, 490, 170, 30);

        getContentPane().add(JPanelCadastro);
        JPanelCadastro.setBounds(20, 10, 960, 570);

        jmArquivo.setText("Arquivo");

        aAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        aAbrir.setText("Abrir");
        aAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aAbrirActionPerformed(evt);
            }
        });
        jmArquivo.add(aAbrir);
        aAbrir.getAccessibleContext().setAccessibleDescription("");

        aNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        aNovo.setText("Novo");
        jmArquivo.add(aNovo);

        aSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        aSalvar.setText("Salvar");
        jmArquivo.add(aSalvar);

        aSalvarComo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        aSalvarComo.setText("Salvar Como");
        jmArquivo.add(aSalvarComo);

        JMenuBarra.add(jmArquivo);

        ePropriedades.setText("Editar");

        eDesfazer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        eDesfazer.setText("Desfazer");
        eDesfazer.setToolTipText("");
        ePropriedades.add(eDesfazer);

        eRefazer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        eRefazer.setText("Refazer");
        ePropriedades.add(eRefazer);

        eCortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        eCortar.setText("Cortar");
        ePropriedades.add(eCortar);

        eCopiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        eCopiar.setText("Copiar");
        ePropriedades.add(eCopiar);

        eColar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        eColar.setText("Colar");
        ePropriedades.add(eColar);

        JMenuBarra.add(ePropriedades);

        JMExibir.setText("Exibir");

        eFerramentas.setText("Barra de Ferramentas");
        JMExibir.add(eFerramentas);

        ePropr.setText("Barra de Propriedades");
        ePropr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eProprActionPerformed(evt);
            }
        });
        JMExibir.add(ePropr);

        eStatus.setText("Barra de Status");
        eStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eStatusActionPerformed(evt);
            }
        });
        JMExibir.add(eStatus);

        eIGrandes.setText("Ícones Grandes");
        eIGrandes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eIGrandesActionPerformed(evt);
            }
        });
        JMExibir.add(eIGrandes);

        eIPequenos.setText("Ícones Pequenos");
        JMExibir.add(eIPequenos);

        eLista.setText("Lista");
        JMExibir.add(eLista);

        eDetalhe.setText("Detalhe");
        JMExibir.add(eDetalhe);

        eClassificar.setText("Classificar Tudo");
        JMExibir.add(eClassificar);

        JMenuBarra.add(JMExibir);

        JMAjuda.setText("Ajuda");

        aSobre.setText("Sobre?");
        JMAjuda.add(aSobre);

        aServicosSup.setText("Serviços e Suporte");
        JMAjuda.add(aServicosSup);

        aAtalhos.setText("Atalhos do Teclado");
        JMAjuda.add(aAtalhos);

        JMenuBarra.add(JMAjuda);

        setJMenuBar(JMenuBarra);

        getAccessibleContext().setAccessibleDescription("");

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1016)/2, (screenSize.height-649)/2, 1016, 649);
    }// </editor-fold>//GEN-END:initComponents

    private void aAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aAbrirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aAbrirActionPerformed

    private void eProprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eProprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eProprActionPerformed

    private void eStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eStatusActionPerformed

    private void eIGrandesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eIGrandesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eIGrandesActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        FuncionarioDAO dao = new FuncionarioDAO();
        
        Funcionario funcionario = new Funcionario();
        EnderecoFuncionario endereco = new EnderecoFuncionario();
        funcionario.setNome(this.fNome.getText());
        funcionario.setNacionalidade(this.fNasciona.getText());
        funcionario.setCpf(this.fCPF.getText());
        funcionario.setTipo("PF");
        funcionario.setRg(this.fRG.getText());
        funcionario.setCtps(this.fCTPS.getText());
        funcionario.setEstado("SP");
        funcionario.setProfissao(this.fProfissao.getText());
        funcionario.setDataNasc(new Date());
        funcionario.setSexo("Masculino");
        funcionario.setEmail(this.fEmail.getText());
        funcionario.setTelefone(this.fTel.getText());
        funcionario.setCelular(this.fCel.getText());

        dao.adiciona(funcionario);
    }//GEN-LAST:event_btnInserirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CadastroFuncionario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMAjuda;
    private javax.swing.JMenu JMExibir;
    private javax.swing.JMenuBar JMenuBarra;
    private javax.swing.JPanel JPanelCadastro;
    private javax.swing.JMenuItem aAbrir;
    private javax.swing.JMenuItem aAtalhos;
    private javax.swing.JMenuItem aNovo;
    private javax.swing.JMenuItem aSalvar;
    private javax.swing.JMenuItem aSalvarComo;
    private javax.swing.JMenuItem aServicosSup;
    private javax.swing.JMenuItem aSobre;
    private javax.swing.JButton bntBusca;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JMenuItem eClassificar;
    private javax.swing.JMenuItem eColar;
    private javax.swing.JMenuItem eCopiar;
    private javax.swing.JMenuItem eCortar;
    private javax.swing.JMenuItem eDesfazer;
    private javax.swing.JMenuItem eDetalhe;
    private javax.swing.JMenuItem eFerramentas;
    private javax.swing.JMenuItem eIGrandes;
    private javax.swing.JMenuItem eIPequenos;
    private javax.swing.JMenuItem eLista;
    private javax.swing.JMenuItem ePropr;
    private javax.swing.JMenu ePropriedades;
    private javax.swing.JMenuItem eRefazer;
    private javax.swing.JMenuItem eStatus;
    private javax.swing.JFormattedTextField fCPF;
    private javax.swing.JFormattedTextField fCTPS;
    private javax.swing.JFormattedTextField fCel;
    private javax.swing.JComboBox fCivil;
    private javax.swing.JTextField fCodigo;
    private javax.swing.JTextField fEmail;
    private javax.swing.JComboBox fMasc;
    private javax.swing.JFormattedTextField fNasc;
    private javax.swing.JTextField fNasciona;
    private javax.swing.JTextField fNome;
    private javax.swing.JComboBox fPessoa;
    private javax.swing.JTextField fProfissao;
    private javax.swing.JFormattedTextField fRG;
    private javax.swing.JFormattedTextField fTel;
    private javax.swing.JMenu jmArquivo;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCTPS;
    private javax.swing.JLabel lblCel;
    private javax.swing.JLabel lblCivil;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNacionalidade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblProf;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblTipo;
    // End of variables declaration//GEN-END:variables
}
