/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tcc.ui;

import java.util.Date;
import tcc.dao.FuncionarioDAO;
import tcc.model.EnderecoFuncionario;
import tcc.model.Funcionario;

/**
 *
 * @author Affero
 */
public class CadastroFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        JPanelCadastro = new javax.swing.JPanel();
        bntBusca = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        fCodigo = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        fNome = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        fEmail = new javax.swing.JTextField();
        btnInserir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblNacionalidade = new javax.swing.JLabel();
        fNasciona = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        fCPF = new javax.swing.JFormattedTextField();
        fPessoa = new javax.swing.JComboBox();
        lblRG = new javax.swing.JLabel();
        fRG = new javax.swing.JFormattedTextField();
        fCTPS = new javax.swing.JFormattedTextField();
        lblCTPS = new javax.swing.JLabel();
        lblCivil = new javax.swing.JLabel();
        fCivil = new javax.swing.JComboBox();
        lblProf = new javax.swing.JLabel();
        fProfissao = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        fNasc = new javax.swing.JFormattedTextField();
        lblSexo = new javax.swing.JLabel();
        fSexo = new javax.swing.JComboBox();
        lblTel = new javax.swing.JLabel();
        fTel = new javax.swing.JFormattedTextField();
        lblCel = new javax.swing.JLabel();
        fCel = new javax.swing.JFormattedTextField();
        lblAdmissao = new javax.swing.JLabel();
        lblDemissao = new javax.swing.JLabel();
        fAdmissao = new javax.swing.JFormattedTextField();
        fDemissao = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        fEnd1 = new javax.swing.JTextField();
        fEnd2 = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        fCidade = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        fCep = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        fUF = new javax.swing.JComboBox();
        JMenuBarra = new javax.swing.JMenuBar();
        JMAjuda = new javax.swing.JMenu();
        aSobre = new javax.swing.JMenuItem();
        aServicosSup = new javax.swing.JMenuItem();
        aAtalhos = new javax.swing.JMenuItem();

        setTitle("Cadastro de Clientes");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Menu"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        JPanelCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPanelCadastro.setLayout(null);

        bntBusca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntBusca.setText("Busca");
        JPanelCadastro.add(bntBusca);
        bntBusca.setBounds(240, 10, 90, 30);

        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCodigo.setText("Código");
        JPanelCadastro.add(lblCodigo);
        lblCodigo.setBounds(30, 10, 60, 17);

        fCodigo.setName("fCodigo"); // NOI18N
        JPanelCadastro.add(fCodigo);
        fCodigo.setBounds(150, 10, 79, 30);

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNome.setText("Nome");
        JPanelCadastro.add(lblNome);
        lblNome.setBounds(30, 50, 70, 17);
        JPanelCadastro.add(fNome);
        fNome.setBounds(150, 50, 610, 30);

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("E-mail");
        JPanelCadastro.add(lblEmail);
        lblEmail.setBounds(30, 500, 36, 17);
        JPanelCadastro.add(fEmail);
        fEmail.setBounds(150, 500, 490, 30);

        btnInserir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        JPanelCadastro.add(btnInserir);
        btnInserir.setBounds(20, 580, 86, 30);

        btnAtualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAtualizar.setText("Atualizar");
        JPanelCadastro.add(btnAtualizar);
        btnAtualizar.setBounds(120, 580, 100, 30);

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        JPanelCadastro.add(btnExcluir);
        btnExcluir.setBounds(230, 580, 86, 30);

        btnSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        JPanelCadastro.add(btnSair);
        btnSair.setBounds(570, 580, 73, 30);

        lblNacionalidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNacionalidade.setText("Nacionalidade");
        JPanelCadastro.add(lblNacionalidade);
        lblNacionalidade.setBounds(390, 460, 120, 30);

        fNasciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNascionaActionPerformed(evt);
            }
        });
        JPanelCadastro.add(fNasciona);
        fNasciona.setBounds(520, 460, 120, 30);

        lblCPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCPF.setText("CPF");
        JPanelCadastro.add(lblCPF);
        lblCPF.setBounds(30, 130, 24, 17);

        lblTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTipo.setText("Tipo");
        JPanelCadastro.add(lblTipo);
        lblTipo.setBounds(300, 170, 50, 30);

        try {
            fCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JPanelCadastro.add(fCPF);
        fCPF.setBounds(150, 130, 290, 30);

        fPessoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fPessoa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Física", "Juridica" }));
        JPanelCadastro.add(fPessoa);
        fPessoa.setBounds(350, 170, 90, 30);

        lblRG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRG.setText("RG");
        JPanelCadastro.add(lblRG);
        lblRG.setBounds(30, 90, 30, 30);

        try {
            fRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-###-###/#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JPanelCadastro.add(fRG);
        fRG.setBounds(150, 90, 290, 30);
        JPanelCadastro.add(fCTPS);
        fCTPS.setBounds(150, 170, 140, 30);

        lblCTPS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCTPS.setText("Número CTPS");
        JPanelCadastro.add(lblCTPS);
        lblCTPS.setBounds(30, 170, 110, 30);

        lblCivil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCivil.setText("Estado Civil");
        JPanelCadastro.add(lblCivil);
        lblCivil.setBounds(30, 210, 100, 30);

        fCivil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Casado", "Solteiro" }));
        fCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fCivilActionPerformed(evt);
            }
        });
        JPanelCadastro.add(fCivil);
        fCivil.setBounds(150, 210, 110, 30);

        lblProf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblProf.setText("Profissão");
        JPanelCadastro.add(lblProf);
        lblProf.setBounds(30, 420, 90, 17);
        JPanelCadastro.add(fProfissao);
        fProfissao.setBounds(150, 420, 490, 30);

        lblData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblData.setText("Data de Nasc");
        JPanelCadastro.add(lblData);
        lblData.setBounds(30, 460, 110, 30);

        try {
            fNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JPanelCadastro.add(fNasc);
        fNasc.setBounds(150, 460, 120, 30);

        lblSexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSexo.setText("Sexo");
        JPanelCadastro.add(lblSexo);
        lblSexo.setBounds(280, 210, 60, 30);

        fSexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        JPanelCadastro.add(fSexo);
        fSexo.setBounds(330, 210, 110, 30);

        lblTel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTel.setText("Telefone");
        JPanelCadastro.add(lblTel);
        lblTel.setBounds(30, 540, 80, 30);

        try {
            fTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JPanelCadastro.add(fTel);
        fTel.setBounds(150, 540, 170, 30);

        lblCel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCel.setText("Celular");
        JPanelCadastro.add(lblCel);
        lblCel.setBounds(390, 540, 70, 30);

        try {
            fCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JPanelCadastro.add(fCel);
        fCel.setBounds(470, 540, 170, 30);

        lblAdmissao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAdmissao.setText("Data Admissão");
        JPanelCadastro.add(lblAdmissao);
        lblAdmissao.setBounds(500, 90, 120, 20);

        lblDemissao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDemissao.setText("Data Demissão");
        JPanelCadastro.add(lblDemissao);
        lblDemissao.setBounds(500, 130, 120, 30);

        try {
            fAdmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JPanelCadastro.add(fAdmissao);
        fAdmissao.setBounds(640, 90, 120, 30);

        try {
            fDemissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JPanelCadastro.add(fDemissao);
        fDemissao.setBounds(640, 130, 120, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Endereço");
        JPanelCadastro.add(jLabel1);
        jLabel1.setBounds(30, 260, 100, 17);
        JPanelCadastro.add(fEnd1);
        fEnd1.setBounds(150, 260, 290, 30);
        JPanelCadastro.add(fEnd2);
        fEnd2.setBounds(150, 300, 290, 30);

        lblCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCidade.setText("Cidade");
        JPanelCadastro.add(lblCidade);
        lblCidade.setBounds(30, 380, 80, 17);
        JPanelCadastro.add(fCidade);
        fCidade.setBounds(150, 380, 160, 30);

        lblCep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCep.setText("Cep");
        JPanelCadastro.add(lblCep);
        lblCep.setBounds(30, 340, 40, 17);

        try {
            fCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JPanelCadastro.add(fCep);
        fCep.setBounds(150, 340, 160, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("UF");
        JPanelCadastro.add(jLabel2);
        jLabel2.setBounds(330, 340, 16, 17);

        fUF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fUF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AL", "AP", "AM", "BA", "CE", "DF ", "ES", "GO", "MA", "MT", "MS", "MG", "PR", "PB", "PA", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "SP", "TO" }));
        JPanelCadastro.add(fUF);
        fUF.setBounds(370, 340, 70, 30);

        getContentPane().add(JPanelCadastro);
        JPanelCadastro.setBounds(10, 10, 960, 620);

        JMAjuda.setText("Ajuda");

        aSobre.setText("Sobre?");
        JMAjuda.add(aSobre);

        aServicosSup.setText("Serviços e Suporte");
        JMAjuda.add(aServicosSup);

        aAtalhos.setText("Atalhos do Teclado");
        JMAjuda.add(aAtalhos);

        JMenuBarra.add(JMAjuda);

        setJMenuBar(JMenuBarra);

        getAccessibleContext().setAccessibleDescription("");

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1016)/2, (screenSize.height-709)/2, 1016, 709);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        FuncionarioDAO dao = new FuncionarioDAO();
        
        Funcionario funcionario = new Funcionario();
        EnderecoFuncionario endereco = new EnderecoFuncionario();
        funcionario.setNome(this.fNome.getText());
        funcionario.setNacionalidade(this.fNasciona.getText());
        funcionario.setCpf(this.fCPF.getText());
        funcionario.setTipo("PF");
        funcionario.setRg(this.fRG.getText());
        //funcionario.setCtps(this.fCTPS.getText());
        funcionario.setEstadoCivil("SP");
        funcionario.setCtps(this.fCTPS.getText());
        funcionario.setEstadoCivil("Solteiro");
        funcionario.setProfissao(this.fProfissao.getText());
        funcionario.setDataNasc(new Date());
        funcionario.setSexo("Masculino");
        funcionario.setEmail(this.fEmail.getText());
        funcionario.setTelefone(this.fTel.getText());
        funcionario.setCelular(this.fCel.getText());
        funcionario.setData_admissao(new Date());
        funcionario.setData_demissao(new Date());
        funcionario.setCep(this.fCep.getText());
        funcionario.setEndereco1(this.fEnd1.getText());
        funcionario.setEndereco2(this.fEnd2.getText());
        funcionario.setUf("SP");

        dao.adiciona(funcionario, this);
    }//GEN-LAST:event_btnInserirActionPerformed

    private void fCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fCivilActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void fNascionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNascionaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNascionaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CadastroFuncionario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMAjuda;
    private javax.swing.JMenuBar JMenuBarra;
    private javax.swing.JPanel JPanelCadastro;
    private javax.swing.JMenuItem aAtalhos;
    private javax.swing.JMenuItem aServicosSup;
    private javax.swing.JMenuItem aSobre;
    private javax.swing.JButton bntBusca;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JFormattedTextField fAdmissao;
    private javax.swing.JFormattedTextField fCPF;
    private javax.swing.JFormattedTextField fCTPS;
    private javax.swing.JFormattedTextField fCel;
    private javax.swing.JFormattedTextField fCep;
    private javax.swing.JTextField fCidade;
    private javax.swing.JComboBox fCivil;
    private javax.swing.JTextField fCodigo;
    private javax.swing.JFormattedTextField fDemissao;
    private javax.swing.JTextField fEmail;
    private javax.swing.JTextField fEnd1;
    private javax.swing.JTextField fEnd2;
    private javax.swing.JFormattedTextField fNasc;
    private javax.swing.JTextField fNasciona;
    private javax.swing.JTextField fNome;
    private javax.swing.JComboBox fPessoa;
    private javax.swing.JTextField fProfissao;
    private javax.swing.JFormattedTextField fRG;
    private javax.swing.JComboBox fSexo;
    private javax.swing.JFormattedTextField fTel;
    private javax.swing.JComboBox fUF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAdmissao;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCTPS;
    private javax.swing.JLabel lblCel;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCivil;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDemissao;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNacionalidade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblProf;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblTipo;
    // End of variables declaration//GEN-END:variables
}
