/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tcc.ui;

import java.util.Date;
import tcc.model.Cliente;
import tcc.model.EnderecoCliente;
import tcc.dao.ClienteDAO;

/**
 *
 * @author Affero
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        JPanelCadastro = new javax.swing.JPanel();
        btnBusca = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        eCodigo = new javax.swing.JTextField();
        lblDataAlteracao = new javax.swing.JLabel();
        rdPF = new javax.swing.JRadioButton();
        rdPJ = new javax.swing.JRadioButton();
        lblCNPJ = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        eNome = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        eEndereco = new javax.swing.JTextField();
        eBairro = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        eCidade = new javax.swing.JTextField();
        lblUF = new javax.swing.JLabel();
        eDateAlt = new javax.swing.JFormattedTextField();
        eCNPJ = new javax.swing.JFormattedTextField();
        eCEP = new javax.swing.JFormattedTextField();
        lblTelefone = new javax.swing.JLabel();
        eTel = new javax.swing.JFormattedTextField();
        cbUF = new javax.swing.JComboBox();
        lblEmail = new javax.swing.JLabel();
        eEmail = new javax.swing.JTextField();
        lblCel = new javax.swing.JLabel();
        eCel = new javax.swing.JFormattedTextField();
        btnInserir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        JMenuBarra = new javax.swing.JMenuBar();
        JMArquivo = new javax.swing.JMenu();
        aAbrir = new javax.swing.JMenuItem();
        aNovo = new javax.swing.JMenuItem();
        aSalvar = new javax.swing.JMenuItem();
        aSalvarComo = new javax.swing.JMenuItem();
        EPropriedades = new javax.swing.JMenu();
        eDesfazer = new javax.swing.JMenuItem();
        eRefazer = new javax.swing.JMenuItem();
        eCortar = new javax.swing.JMenuItem();
        eCopiar = new javax.swing.JMenuItem();
        eColar = new javax.swing.JMenuItem();
        JMExibir = new javax.swing.JMenu();
        eFerramentas = new javax.swing.JMenuItem();
        ePropr = new javax.swing.JMenuItem();
        eStatus = new javax.swing.JMenuItem();
        eIGrandes = new javax.swing.JMenuItem();
        eIPequenos = new javax.swing.JMenuItem();
        eLista = new javax.swing.JMenuItem();
        eDetalhe = new javax.swing.JMenuItem();
        eClassificar = new javax.swing.JMenuItem();
        JMAjuda = new javax.swing.JMenu();
        aSobre = new javax.swing.JMenuItem();
        aServicosSup = new javax.swing.JMenuItem();
        aAtalhos = new javax.swing.JMenuItem();

        setTitle("Cadastro de Clientes");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Menu"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        JPanelCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnBusca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBusca.setText("Busca");

        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCodigo.setText("Código");

        eCodigo.setName("eCodigo"); // NOI18N

        lblDataAlteracao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDataAlteracao.setText("Data. Ult. Alteração");

        buttonGroup2.add(rdPF);
        rdPF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdPF.setText("PF");
        rdPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPFActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdPJ);
        rdPJ.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdPJ.setText("PJ");

        lblCNPJ.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCNPJ.setText("C.N.P.J/CPF");

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNome.setText("Nome/Razão Social");

        lblEndereco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEndereco.setText("Endereço");

        lblCep.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCep.setText("Cep");

        lblCidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCidade.setText("Cidade");

        lblUF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUF.setText("UF");

        try {
            eDateAlt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            eCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            eCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        eCEP.setPreferredSize(new java.awt.Dimension(14, 28));

        lblTelefone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTelefone.setText("Telefone");

        try {
            eTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        eTel.setPreferredSize(new java.awt.Dimension(14, 28));

        cbUF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbUF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AL", "AP", "AM", "BA", "CE", "DF ", "ES", "GO", "MA", "MT", "MS", "MG", "PR", "PB", "PA", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "SP", "TO" }));
        cbUF.setName(""); // NOI18N
        cbUF.setPreferredSize(new java.awt.Dimension(14, 28));

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmail.setText("E-mail");

        lblCel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCel.setText("Celular");

        try {
            eCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        eCel.setPreferredSize(new java.awt.Dimension(14, 28));
        eCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eCelActionPerformed(evt);
            }
        });

        btnInserir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAtualizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAtualizar.setText("Atualizar");

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnExcluir.setText("Excluir");

        btnSair.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSair.setText("Sair");

        javax.swing.GroupLayout JPanelCadastroLayout = new javax.swing.GroupLayout(JPanelCadastro);
        JPanelCadastro.setLayout(JPanelCadastroLayout);
        JPanelCadastroLayout.setHorizontalGroup(
            JPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCadastroLayout.createSequentialGroup()
                .addGroup(JPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPanelCadastroLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(eCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btnBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(JPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdPJ)
                            .addComponent(rdPF)
                            .addGroup(JPanelCadastroLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(lblCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(eCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblDataAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(eDateAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelCadastroLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(JPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(JPanelCadastroLayout.createSequentialGroup()
                                .addComponent(lblEndereco)
                                .addGap(8, 8, 8)
                                .addComponent(eEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCep)
                                .addGap(10, 10, 10)
                                .addComponent(eCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPanelCadastroLayout.createSequentialGroup()
                                .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(eNome, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(JPanelCadastroLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(534, 534, 534)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
            .addGroup(JPanelCadastroLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(JPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelCadastroLayout.createSequentialGroup()
                        .addGroup(JPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefone)
                            .addComponent(lblEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelCadastroLayout.createSequentialGroup()
                                .addComponent(eTel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(eEmail)))
                    .addGroup(JPanelCadastroLayout.createSequentialGroup()
                        .addComponent(lblCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(JPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelCadastroLayout.createSequentialGroup()
                                .addComponent(eBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(JPanelCadastroLayout.createSequentialGroup()
                                .addComponent(eCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lblUF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(JPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JPanelCadastroLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(cbUF, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelCadastroLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(eCel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(308, 308, 308))
        );
        JPanelCadastroLayout.setVerticalGroup(
            JPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCadastroLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(JPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelCadastroLayout.createSequentialGroup()
                        .addComponent(rdPJ)
                        .addGap(3, 3, 3)
                        .addComponent(rdPF))
                    .addGroup(JPanelCadastroLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(JPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigo)
                            .addComponent(eCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBusca)
                            .addComponent(lblCNPJ)
                            .addComponent(eCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eDateAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13)
                .addGroup(JPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome)
                    .addComponent(eNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEndereco)
                        .addComponent(eEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCep)
                    .addComponent(eCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(eBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCidade)
                    .addGroup(JPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbUF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUF)))
                .addGap(16, 16, 16)
                .addGroup(JPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTelefone)
                        .addComponent(eTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCel)
                        .addComponent(eCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(JPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addComponent(eEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(JPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInserir)
                    .addComponent(btnAtualizar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair)))
        );

        getContentPane().add(JPanelCadastro);
        JPanelCadastro.setBounds(20, 20, 950, 450);

        JMArquivo.setText("Arquivo");

        aAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        aAbrir.setText("Abrir");
        aAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aAbrirActionPerformed(evt);
            }
        });
        JMArquivo.add(aAbrir);
        aAbrir.getAccessibleContext().setAccessibleDescription("");

        aNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        aNovo.setText("Novo");
        JMArquivo.add(aNovo);

        aSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        aSalvar.setText("Salvar");
        JMArquivo.add(aSalvar);

        aSalvarComo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        aSalvarComo.setText("Salvar Como");
        JMArquivo.add(aSalvarComo);

        JMenuBarra.add(JMArquivo);

        EPropriedades.setText("Editar");

        eDesfazer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        eDesfazer.setText("Desfazer");
        eDesfazer.setToolTipText("");
        EPropriedades.add(eDesfazer);

        eRefazer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        eRefazer.setText("Refazer");
        EPropriedades.add(eRefazer);

        eCortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        eCortar.setText("Cortar");
        EPropriedades.add(eCortar);

        eCopiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        eCopiar.setText("Copiar");
        EPropriedades.add(eCopiar);

        eColar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        eColar.setText("Colar");
        EPropriedades.add(eColar);

        JMenuBarra.add(EPropriedades);

        JMExibir.setText("Exibir");

        eFerramentas.setText("Barra de Ferramentas");
        JMExibir.add(eFerramentas);

        ePropr.setText("Barra de Propriedades");
        ePropr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eProprActionPerformed(evt);
            }
        });
        JMExibir.add(ePropr);

        eStatus.setText("Barra de Status");
        eStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eStatusActionPerformed(evt);
            }
        });
        JMExibir.add(eStatus);

        eIGrandes.setText("Ícones Grandes");
        eIGrandes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eIGrandesActionPerformed(evt);
            }
        });
        JMExibir.add(eIGrandes);

        eIPequenos.setText("Ícones Pequenos");
        JMExibir.add(eIPequenos);

        eLista.setText("Lista");
        JMExibir.add(eLista);

        eDetalhe.setText("Detalhe");
        JMExibir.add(eDetalhe);

        eClassificar.setText("Classificar Tudo");
        JMExibir.add(eClassificar);

        JMenuBarra.add(JMExibir);

        JMAjuda.setText("Ajuda");

        aSobre.setText("Sobre?");
        JMAjuda.add(aSobre);

        aServicosSup.setText("Serviços e Suporte");
        JMAjuda.add(aServicosSup);

        aAtalhos.setText("Atalhos do Teclado");
        JMAjuda.add(aAtalhos);

        JMenuBarra.add(JMAjuda);

        setJMenuBar(JMenuBarra);

        getAccessibleContext().setAccessibleDescription("");

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1016)/2, (screenSize.height-638)/2, 1016, 638);
    }// </editor-fold>//GEN-END:initComponents

    private void aAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aAbrirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aAbrirActionPerformed

    private void rdPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdPFActionPerformed

    private void eProprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eProprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eProprActionPerformed

    private void eStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eStatusActionPerformed

    private void eIGrandesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eIGrandesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eIGrandesActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        ClienteDAO dao = new ClienteDAO();
        
        Cliente cliente = new Cliente();
        EnderecoCliente endereco = new EnderecoCliente();
        cliente.setNome(this.eNome.getText());
        cliente.setCelular(this.eCel.getText());
        cliente.setEmail(this.eEmail.getText());
        cliente.setTelefone(this.eTel.getText());
        cliente.setData_alt(new Date());
        cliente.setTipo("PF");
        cliente.setDocumento(this.eCNPJ.getText());
        endereco.setCep(this.eCEP.getText());
        endereco.setEndereco1(this.eEndereco.getText());
        endereco.setEndereco2(this.eBairro.getText());
        endereco.setCidade(this.eCidade.getText());
        endereco.setUf("SP");
        cliente.setEnd_cliente(endereco);
        
        dao.adiciona(cliente, this);
        
    }//GEN-LAST:event_btnInserirActionPerformed

    private void eCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eCelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eCelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu EPropriedades;
    private javax.swing.JMenu JMAjuda;
    private javax.swing.JMenu JMArquivo;
    private javax.swing.JMenu JMExibir;
    private javax.swing.JMenuBar JMenuBarra;
    private javax.swing.JPanel JPanelCadastro;
    private javax.swing.JMenuItem aAbrir;
    private javax.swing.JMenuItem aAtalhos;
    private javax.swing.JMenuItem aNovo;
    private javax.swing.JMenuItem aSalvar;
    private javax.swing.JMenuItem aSalvarComo;
    private javax.swing.JMenuItem aServicosSup;
    private javax.swing.JMenuItem aSobre;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cbUF;
    private javax.swing.JTextField eBairro;
    private javax.swing.JFormattedTextField eCEP;
    private javax.swing.JFormattedTextField eCNPJ;
    private javax.swing.JFormattedTextField eCel;
    private javax.swing.JTextField eCidade;
    private javax.swing.JMenuItem eClassificar;
    private javax.swing.JTextField eCodigo;
    private javax.swing.JMenuItem eColar;
    private javax.swing.JMenuItem eCopiar;
    private javax.swing.JMenuItem eCortar;
    private javax.swing.JFormattedTextField eDateAlt;
    private javax.swing.JMenuItem eDesfazer;
    private javax.swing.JMenuItem eDetalhe;
    private javax.swing.JTextField eEmail;
    private javax.swing.JTextField eEndereco;
    private javax.swing.JMenuItem eFerramentas;
    private javax.swing.JMenuItem eIGrandes;
    private javax.swing.JMenuItem eIPequenos;
    private javax.swing.JMenuItem eLista;
    private javax.swing.JTextField eNome;
    private javax.swing.JMenuItem ePropr;
    private javax.swing.JMenuItem eRefazer;
    private javax.swing.JMenuItem eStatus;
    private javax.swing.JFormattedTextField eTel;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblCel;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDataAlteracao;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblUF;
    private javax.swing.JRadioButton rdPF;
    private javax.swing.JRadioButton rdPJ;
    // End of variables declaration//GEN-END:variables
}
